### ISSUE TITLE
Invalid response: display "Login Failed" even there was no login attempt

### ISSUE THREAD

**Issue by Wootack** [snuhcs-course/project-ta-project#3]
# Issue type
Invalid response

# Invalid response at
The first login page

# Valid interaction
When the user runs the app for the first time, the app should not display "Login Failed."

# Issue body
Even if there was no attempt to log in since running the app, it displays "Login Failed."
That message should appear only when there is an invalid login attempt.

**Comment by eu1jun** [comment]
Thanks for pointing out the inconsistency on the login page. I've addressed the "Login Failed" message displaying erroneously upon initial app launch.

The solution has been implemented in the pull request [#5].
