### ISSUE TITLE
Feature: rejecting invalid user input at sign up stage

### ISSUE THREAD

**Issue by Wootack** [snuhcs-course/project-ta-project#6]
# Issue Type
Feature request

# Feature required at
Sign Up page

# Feature details
On the sign-up page, the user enters the required inputs. However, the inputs could be invalid, and the application should be able to notify the user about the invalid input.
1. If the password and re-entered password are not identical, the application should deny the sign-up process and make the user enter and verify the password in a proper way.
2. If the email address user had entered is already registered, the application should deny the sign-up process and announce it to the user.

**Comment by eu1jun** [comment]
2. should be handled during implementing 'Create & delete account' task because it needs to check whether the email is already registered or not on the server. For the 1., I can implement them in advance, but it seems more effective to consider the registering logic as a whole.
